export const flagCodes = {
    "Greece": "GRC",
    "France": "FRA",
    "United States": "USA",
    "United Kingdom": "GBR",
    "Sweden": "SWE",
    "Belgium": "BEL",
    "United States": "USA",
    "Netherlands": "NED",
    "Germany": "GER",
    "Austria": "AUT",
    "Italy": "ITA",
    "Australia": "AUS",
    "Mexico": "MEX",
    "Canada": "CAN",
    "Russia": "RUS",
    "Yugoslavia": "YUG",
    "South Korea": "KOR",
    "Spain": "ESP",
    "Norway": "NOR",
    "Greece": "GRC",
    "Italy": "ITA",
    "China": "CHN",
    "Canada": "CAN",
    "Russia": "RUS",
    "South Korea": "KOR",
    "Japan": "JPN",
    "China": "CHN",
    "Finland": "FIN",
};